routes/web.php
<?php

use App\Http\Controllers\Back\BlogController;
use App\Http\Controllers\Back\ContactController;
use App\Http\Controllers\Back\DeskripsiTeamController;
use App\Http\Controllers\Back\KategoriController;
use App\Http\Controllers\Back\PesanController;
use App\Http\Controllers\Back\ProfileController;
use App\Http\Controllers\Back\ProfileGambarController;
use App\Http\Controllers\Back\SlideController;
use App\Http\Controllers\Back\TeamController;
use App\Http\Controllers\Front\FrontendController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontendController::class, 'index'])->name('homepage');
Route::get('/blog/detail/{slug}', [FrontendController::class, 'detail'])->name('detail');
Route::post('/kirim-pesan', [FrontendController::class, 'store'])->name('kirimpesan');


Auth::routes([
    'register' => false, // Register Routes...
    'reset' => false, // Reset Password Routes...
    'verify' => false, // Email Verification Routes...
]);


Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');
Route::resource('slide', SlideController::class);
Route::resource('profile', ProfileController::class);
Route::resource('profile-gambar', ProfileGambarController::class);
Route::resource('kategori', KategoriController::class);
Route::resource('blog', BlogController::class);
Route::resource('team', TeamController::class);
Route::resource('deskripsi-team', DeskripsiTeamController::class);
Route::resource('contact', ContactController::class);
Route::resource('pesan', PesanController::class);

app/Models/ProfileGambar.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ProfileGambar extends Model
{
    use HasFactory;

    protected $fillable = [
        'judul',
        'deskripsi',
        'profile_gambar',
        'status',
    ];
}

app/Http/Controllers/Back/ProfileGambarController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Models\ProfileGambar;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ProfileGambarController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }


    public function index()
    {
        $profile_gambar = ProfileGambar::all();
        return view('admin.profile-gambar.index', compact('profile_gambar'));
    }


    public function create()
    {
        return view('admin.profile-gambar.create');
    }


    public function store(Request $request)
    {
        request()->validate([
            'profile_gambar' => 'required|image|mimes:jpeg,png,jpg,gif,svg',
            'judul' => 'required',
            'deskripsi' => 'required',
        ]);

        if (empty($request->file('profile_gambar'))) {
            ProfileGambar::create([
                'judul' => $request->judul,
                'deskripsi' => $request->deskripsi,
                'status' => $request->status == TRUE ? '1':'0',
            ]);

            toast('Data Gagal dibuat','error');

            return redirect()->back()->with('error', 'Gambar Slide tidak boleh kosong');

        } else {

            ProfileGambar::create([
                'judul' => $request->judul,
                'deskripsi' => $request->deskripsi,
                'status' => $request->status == TRUE ? '1':'0',
                'profile_gambar' => $request->file('profile_gambar')->store('profil-gambar'),
            ]);
        }

        toast('Data Berhasil dibuat','success');

        return redirect()->route('profile-gambar.index')->with('success', 'Data berhasil ditambahkan');
    }


    public function edit($id)
    {
        $profile_gambar = ProfileGambar::find(decrypt($id));
        return view('admin.profile-gambar.edit', compact('profile_gambar'));
    }


    public function update(Request $request, $id)
    {
        request()->validate([
            'profile_gambar' => 'image|mimes:jpeg,png,jpg,gif,svg',
            'judul' => 'required',
            'deskripsi' => 'required',
        ]);

        if (empty($request->file('profile_gambar'))) {
            $profile_gambar = ProfileGambar::find($id);
            $profile_gambar->update([
                'judul' => $request->judul,
                'deskripsi' => $request->deskripsi,
                'status' => $request->status == TRUE ? '1':'0',
            ]);

            toast('Data Berhasil diupdate','success');

            return redirect()->route('profile-gambar.index')->with('error', 'Gambar Slide tidak boleh kosong');

        } else {
            $profile_gambar = ProfileGambar::find($id);
            Storage::delete($profile_gambar->profile_gambar);
            $profile_gambar->update([
                'judul' => $request->judul,
                'deskripsi' => $request->deskripsi,
                'status' => $request->status == TRUE ? '1':'0',
                'profile_gambar' => $request->file('profile_gambar')->store('profil-gambar'),
            ]);
        }

        toast('Data Berhasil diupdate','success');

        return redirect()->route('profile-gambar.index')->with('success', 'Data berhasil diubah');
    }


    public function destroy($id)
    {
        $profile_gambar = ProfileGambar::find($id);
        $profile_gambar->delete();

        toast('Data Berhasil dihapus','success');

        return redirect()->route('profile-gambar.index')->with('success', 'Data berhasil dihapus');
    }
}

resources/views/admin/profile-gambar/create.blade.php
@extends('admin.layout.layout', ['menu' => 'componen', 'submenu' => 'slide'])

@section('title', 'Profil Gambar')

@section('content')
    <div class="">

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Create Data @yield('title')</h5>

                <!-- General Form Elements -->
                <form action="{{ route('profile-gambar.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="row mb-3">
                        <label for="inputText" class="col-sm-2 col-form-label">Judul</label>
                        <div class="col-sm-10">
                            <input name="judul" id="judul" type="text" class="form-control @error('judul') is-invalid @enderror" placeholder="Judul Profil Gambar" value="{{ old('judul' ) }}">
                        </div>
                        @error('judul')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>


                    <div class="row mb-3">
                        <label for="inputPassword" class="col-sm-2 col-form-label">Deskripsi</label>
                        <div class="col-sm-10">
                            <textarea name="deskripsi" id="deskripsi" class="form-control @error('deskripsi') is-invalid @enderror" style="height: 100px" placeholder="Deskripsi Gambar" value="{{ old('deskripsi' ) }}"></textarea>
                        </div>
                        @error('deskripsi')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>

                    <div class="row mb-3">
                        <label for="inputNumber" class="col-sm-2 col-form-label">Upload Gambar</label>
                        <div class="col-sm-10">
                            <input name="profile_gambar" id="profile_gambar" class="form-control @error('profil_gambar') is-invalid @enderror" type="file" value="{{ old('profile_gambar' ) }}">
                        </div>
                    </div>

                    <div class="row mb-5">
                        <label class="col-sm-2 col-form-label">Status</label>
                        <div class="col-sm-10">
                            <div class="form-check form-switch">
                                <input name="status" id="status" class="form-check-input" type="checkbox">
                                @error('status')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                                <label class="form-check-label" for="flexSwitchCheckChecked">Unpublish / Publish</label>
                            </div>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label class="col-sm-2 col-form-label">Submit Button</label>
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary">Tambah Data</button>
                            <button type="reset" class="btn btn-danger">Reset Data</button>
                        </div>
                    </div>

                </form>
                <!-- End General Form Elements -->

            </div>
        </div>

    </div>

@endsection

resources/views/admin/profile-gambar/edit.blade.php
@extends('admin.layout.layout', ['menu' => 'componen', 'submenu' => 'slide'])

@section('title', 'Profil Gambar')

@section('content')
    <div class="">

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Edit Data @yield('title')</h5>

                <div class="filter">
                    <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                        <li class="dropdown-header text-start">
                            <h6>ACTION</h6>
                        </li>

                        <li><a class="dropdown-item" href="{{ route('profile-gambar.index') }}">Kembali</a></li>

                    </ul>
                </div>

                <!-- General Form Elements -->
                <form action="{{ route('profile-gambar.update', $profile_gambar->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="row mb-3">
                        <label for="inputText" class="col-sm-2 col-form-label">Judul</label>
                        <div class="col-sm-10">
                            <input name="judul" id="judul" type="text" class="form-control @error('judul') is-invalid @enderror" placeholder="Judul Profil Gambar" value="{{ $profile_gambar->judul }}">
                        </div>
                        @error('judul')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>


                    <div class="row mb-3">
                        <label for="inputPassword" class="col-sm-2 col-form-label">Deskripsi</label>
                        <div class="col-sm-10">
                            <textarea name="deskripsi" id="deskripsi" class="form-control @error('deskripsi') is-invalid @enderror" style="height: 100px" placeholder="Deskripsi Gambar" value="{{ old('deskripsi' ) }}">{{ $profile_gambar->deskripsi }}</textarea>
                        </div>
                        @error('deskripsi')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>

                    <div class="row mb-3">
                        <label for="inputNumber" class="col-sm-2 col-form-label">Upload Gambar</label>
                        <div class="col-sm-10">
                            <input name="profile_gambar" id="profile_gambar" class="form-control @error('profil_gambar') is-invalid @enderror" type="file" value="{{ old('profile_gambar' ) }}">
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label for="inputNumber" class="col-sm-2 col-form-label">Gambar saat ini</label>
                        <div class="col-sm-10">
                            <img src="{{ asset('storage/'.$profile_gambar->profile_gambar) }}" alt="{{ $profile_gambar->judul }}" width="100px">
                        </div>
                    </div>

                    <div class="row mb-5">
                        <label class="col-sm-2 col-form-label">Status</label>
                        <div class="col-sm-10">
                            <div class="form-check form-switch">
                                <input type="hidden" name="status" id="status" value="0">
                                <input name="status" id="status" class="form-check-input" type="checkbox" value="1" {{ $profile_gambar->status || old('status', 0) === 1 ? 'checked':'' }}>
                                <label class="form-check-label" for="flexSwitchCheckChecked">Publish</label>
                            </div>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label class="col-sm-2 col-form-label">Submit Button</label>
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary">Update Data</button>
                        </div>
                    </div>

                </form>

                <div class="row mb-3">
                    <label class="col-sm-2 col-form-label">Delete Data</label>
                    <div class="col-sm-10">
                        <form action="{{ route('profile-gambar.destroy', $profile_gambar->id ) }}" onsubmit="return confirm('Yakin anda akan menghapus data {{ $profile_gambar->judul }}?')" method="POST" class="d-inline">
                            @csrf
                            @method('delete')
                            <button class="btn btn-danger">Delete Data</button>
                        </form>
                    </div>
                </div>
                <!-- End General Form Elements -->

            </div>
        </div>

    </div>

@endsection

resources/views/admin/profile-gambar/index.blade.php
@extends('admin.layout.layout', ['menu' => 'componen', 'submenu' => 'slide'])

@section('title', 'Profile Gambar')

@section('content')
<!-- Recent Sales -->
<div class="col-12">
    <div class="card recent-sales overflow-auto">

        <div class="filter">
            <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                <li class="dropdown-header text-start">
                    <h6>ACTION</h6>
                </li>

                <li><a class="dropdown-item" href="{{ route('profile-gambar.create') }}">Tambah</a></li>
            </ul>
        </div>

        <div class="card-body">
            <h5 class="card-title">Data <span>| @yield('title')</span></h5>

            <table class="table table-borderless datatable">
                <thead>
                    <tr>
                        <th scope="col">Gambar</th>
                        <th scope="col">Title</th>
                        <th scope="col">Deskripsi</th>
                        <th scope="col">Status</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($profile_gambar as $item)
                    <tr>
                        <td>
                            @if ($item->profile_gambar)
                            <img src="{{ asset('storage/'. $item->profile_gambar ) }}" alt="{{ $item->judul }}" width="100px">
                            @else
                            <img src="{{ asset('storage/'. $item->profile_gambar ) }}" alt="{{ $item->judul }}" width="100px">
                            @endif
                        </td>
                        <td><a href="{{ route('profile-gambar.edit', encrypt($item->id) ) }}" class="text-primary">{{\Illuminate\Support\Str::words($item->judul, 5,'....') }}</a></td>
                        <td>{{\Illuminate\Support\Str::words($item->deskripsi, 5,'....') }}</td>
                        <td>
                            @if ($item->status == 1)
                            <span class="badge bg-success">Publish</span>
                            @else
                            <span class="badge bg-danger">Unpublish</span>
                            @endif
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>

        </div>

    </div>
</div>
<!-- End Recent Sales -->
@endsection