routes/web.php
<?php

use App\Http\Controllers\Back\BlogController;
use App\Http\Controllers\Back\ContactController;
use App\Http\Controllers\Back\DeskripsiTeamController;
use App\Http\Controllers\Back\KategoriController;
use App\Http\Controllers\Back\PesanController;
use App\Http\Controllers\Back\ProfileController;
use App\Http\Controllers\Back\ProfileGambarController;
use App\Http\Controllers\Back\SlideController;
use App\Http\Controllers\Back\TeamController;
use App\Http\Controllers\Front\FrontendController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontendController::class, 'index'])->name('homepage');
Route::get('/blog/detail/{slug}', [FrontendController::class, 'detail'])->name('detail');
Route::post('/kirim-pesan', [FrontendController::class, 'store'])->name('kirimpesan');


Auth::routes([
    'register' => false, // Register Routes...
    'reset' => false, // Reset Password Routes...
    'verify' => false, // Email Verification Routes...
]);


Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');
Route::resource('slide', SlideController::class);
Route::resource('profile', ProfileController::class);
Route::resource('profile-gambar', ProfileGambarController::class);
Route::resource('kategori', KategoriController::class);
Route::resource('blog', BlogController::class);
Route::resource('team', TeamController::class);
Route::resource('deskripsi-team', DeskripsiTeamController::class);
Route::resource('contact', ContactController::class);
Route::resource('pesan', PesanController::class);

app/Models/Team.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Team extends Model
{
    use HasFactory;

    protected $fillable = [
        'nama_team',
        'foto_team',
        'jabatan_team',
        'facebook_team',
        'instagram_team',
    ];
}

app/Http/Controllers/Back/TeamController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Models\Team;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class TeamController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }


    public function index()
    {
        $teams = Team::all();
        return view('admin.team.index', compact('teams'));
    }


    public function create()
    {
        return view('admin.team.create');
    }


    public function store(Request $request)
    {
        $request->validate([
            'nama_team' => 'required',
            'foto_team' => 'required|image|mimes:jpeg,png,jpg,gif,svg',
            'jabatan_team' => 'required',
        ]);

        if (empty($request->file('foto_team'))) {
            Team::create([
                'nama_team' => $request->nama_team,
                'jabatan_team' => $request->jabatan_team,
                'facebook_team' => $request->facebook_team,
                'instagram_team' => $request->instagram_team,
            ]);

            toast('Data Gagal dibuat','error');

            return redirect()->route('team.index')->with('error', 'Gambar Slide tidak boleh kosong');

        } else {

            Team::create([
                'nama_team' => $request->nama_team,
                'jabatan_team' => $request->jabatan_team,
                'facebook_team' => $request->facebook_team,
                'instagram_team' => $request->instagram_team,
                'foto_team' => $request->file('foto_team')->store('foto-team'),
            ]);
        }

        toast('Data Berhasil dibuat','success');

        return redirect()->route('team.index')->with('success', 'Data berhasil ditambahkan');
    }


    public function edit($id)
    {
        $team = Team::findOrFail(decrypt($id));
        return view('admin.team.edit', compact('team'));
    }


    public function update(Request $request, $id)
    {
        $request->validate([
            'nama_team' => 'required',
            'foto_team' => 'image|mimes:jpeg,png,jpg,gif,svg',
            'jabatan_team' => 'required',
            'facebook_team' => 'required',
            'instagram_team' => 'required',
        ]);

        if (empty($request->file('foto_team'))) {
            Team::findOrFail($id)->update([
                'nama_team' => $request->nama_team,
                'jabatan_team' => $request->jabatan_team,
                'facebook_team' => $request->facebook_team,
                'instagram_team' => $request->instagram_team,
            ]);

            toast('Data Berhasil diupdate','success');

            return redirect()->route('team.index')->with('error', 'Gambar Slide tidak boleh kosong');

        } else {

            $team = Team::findOrFail($id);
            Storage::delete($team->foto_team);
            Team::findOrFail($id)->update([
                'nama_team' => $request->nama_team,
                'jabatan_team' => $request->jabatan_team,
                'facebook_team' => $request->facebook_team,
                'instagram_team' => $request->instagram_team,
                'foto_team' => $request->file('foto_team')->store('foto-team'),
            ]);
        }

        toast('Data Berhasil diupdate','success');

        return redirect()->route('team.index')->with('success', 'Data berhasil diubah');
    }


    public function destroy($id)
    {
        $team = Team::findOrFail($id);
        Storage::delete($team->foto_team);
        $team->delete();

        toast('Data Berhasil dihapus','success');

        return redirect()->route('team.index')->with('success', 'Data berhasil dihapus');
    }

}

resources/views/admin/team/create.blade.php
@extends('admin.layout.layout', ['menu' => 'componen', 'submenu' => 'slide'])

@section('title', 'Team')

@section('content')
    <div class="">

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Create Data @yield('title')</h5>

                <!-- General Form Elements -->
                <form action="{{ route('team.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="row mb-3">
                        <label for="inputText" class="col-sm-2 col-form-label">Nama Team</label>
                        <div class="col-sm-10">
                            <input name="nama_team" id="nama_team" type="text" class="form-control @error('nama_team') is-invalid @enderror" placeholder="Nama Team" value="{{ old('nama_team' ) }}">
                        </div>
                        @error('nama_team')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>

                    <div class="row mb-3">
                        <label for="inputText" class="col-sm-2 col-form-label">Jabatan Team</label>
                        <div class="col-sm-10">
                            <input name="jabatan_team" id="jabatan_team" type="text" class="form-control @error('jabatan_team') is-invalid @enderror" placeholder="Jabatan Team" value="{{ old('jabatan_team' ) }}">
                        </div>
                        @error('jabatan_team')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>


                    <div class="row mb-3">
                        <label for="inputText" class="col-sm-2 col-form-label">Link Facebook</label>
                        <div class="col-sm-10">
                            <input name="facebook_team" id="facebook_team" type="text" class="form-control @error('facebook_team') is-invalid @enderror" placeholder="https://facebook.com/username" value="{{ old('facebook_team' ) }}">
                        </div>
                        @error('facebook_team')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>



                    <div class="row mb-3">
                        <label for="inputText" class="col-sm-2 col-form-label">Link Instagram</label>
                        <div class="col-sm-10">
                            <input name="instagram_team" id="instagram_team" type="text" class="form-control @error('instagram_team') is-invalid @enderror" placeholder="https://instagram.com/username" value="{{ old('instagram_team' ) }}">
                        </div>
                        @error('instagram_team')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>


                    <div class="row mb-3">
                        <label for="inputNumber" class="col-sm-2 col-form-label">Upload Gambar</label>
                        <div class="col-sm-10">
                            <input name="foto_team" id="foto_team" class="form-control @error('foto_team') is-invalid @enderror" type="file" value="{{ old('foto_team' ) }}">
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label class="col-sm-2 col-form-label">Submit Button</label>
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary">Tambah Data</button>
                            <button type="reset" class="btn btn-danger">Reset Data</button>
                        </div>
                    </div>

                </form>
                <!-- End General Form Elements -->

            </div>
        </div>

    </div>

@endsection

resources/views/admin/team/edit.blade.php
@extends('admin.layout.layout', ['menu' => 'componen', 'submenu' => 'slide'])

@section('title', 'Team')

@section('content')
    <div class="">

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Edit Data @yield('title')</h5>

                <div class="filter">
                    <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                        <li class="dropdown-header text-start">
                            <h6>ACTION</h6>
                        </li>

                        <li><a class="dropdown-item" href="{{ route('team.index') }}">Kembali</a></li>

                    </ul>
                </div>

                <!-- General Form Elements -->
                <form action="{{ route('team.update', $team->id ) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="row mb-3">
                        <label for="inputText" class="col-sm-2 col-form-label">Nama Team</label>
                        <div class="col-sm-10">
                            <input name="nama_team" id="nama_team" type="text" class="form-control @error('nama_team') is-invalid @enderror" placeholder="Nama Team" value="{{ $team->nama_team }}">
                        </div>
                        @error('nama_team')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>

                    <div class="row mb-3">
                        <label for="inputText" class="col-sm-2 col-form-label">Jabatan Team</label>
                        <div class="col-sm-10">
                            <input name="jabatan_team" id="jabatan_team" type="text" class="form-control @error('jabatan_team') is-invalid @enderror" placeholder="Jabatan Team" value="{{ $team->jabatan_team }}">
                        </div>
                        @error('jabatan_team')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>


                    <div class="row mb-3">
                        <label for="inputText" class="col-sm-2 col-form-label">Link Facebook</label>
                        <div class="col-sm-10">
                            <input name="facebook_team" id="facebook_team" type="text" class="form-control @error('facebook_team') is-invalid @enderror" placeholder="https://facebook.com/username" value="{{ $team->facebook_team }}">
                        </div>
                        @error('facebook_team')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>



                    <div class="row mb-3">
                        <label for="inputText" class="col-sm-2 col-form-label">Link Instagram</label>
                        <div class="col-sm-10">
                            <input name="instagram_team" id="instagram_team" type="text" class="form-control @error('instagram_team') is-invalid @enderror" placeholder="https://instagram.com/username" value="{{ $team->instagram_team }}">
                        </div>
                        @error('instagram_team')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>


                    <div class="row mb-3">
                        <label for="inputNumber" class="col-sm-2 col-form-label">Upload Gambar</label>
                        <div class="col-sm-10">
                            <input name="foto_team" id="foto_team" class="form-control @error('foto_team') is-invalid @enderror" type="file" value="{{ old('foto_team' ) }}">
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label for="inputNumber" class="col-sm-2 col-form-label">Gambar saat ini</label>
                        <div class="col-sm-10">
                            <img src="{{ asset('storage/'.$team->foto_team) }}" alt="{{ $team->nama_team }}" width="100px">
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label class="col-sm-2 col-form-label">Submit Button</label>
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary">Update Data</button>
                        </div>
                    </div>

                </form>
                <!-- End General Form Elements -->

                <div class="row mb-3">
                    <label class="col-sm-2 col-form-label">Delete Data</label>
                    <div class="col-sm-10">
                        <form action="{{ route('team.destroy', $team->id ) }}" onsubmit="return confirm('Yakin anda akan menghapus data {{ $team->nama_team }}?')" method="POST" class="d-inline">
                            @csrf
                            @method('delete')
                            <button class="btn btn-danger">Delete Data</button>
                        </form>
                    </div>
                </div>
                <!-- End General Form Elements -->

            </div>
        </div>

    </div>

@endsection

resources/views/admin/team/index.blade.php
@extends('admin.layout.layout', ['menu' => 'componen', 'submenu' => 'slide'])

@section('title', 'Team')

@section('content')
<!-- Recent Sales -->
<div class="col-12">
    <div class="card recent-sales overflow-auto">

        <div class="filter">
            <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                <li class="dropdown-header text-start">
                    <h6>ACTION</h6>
                </li>

                <li><a class="dropdown-item" href="{{ route('team.create') }}">Tambah</a></li>
            </ul>
        </div>

        <div class="card-body">
            <h5 class="card-title">Data <span>| @yield('title')</span></h5>

            <table class="table table-borderless datatable">
                <thead>
                    <tr>
                        <th scope="col">Foto</th>
                        <th scope="col">Nama</th>
                        <th scope="col">Jabatan</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($teams as $item)
                    <tr>
                        <td>
                            @if ($item->foto_team)
                            <img src="{{ asset('storage/'. $item->foto_team ) }}" alt="{{ $item->nama_team }}" width="100px">
                            @else
                            <img src="{{ asset('storage/'. $item->foto_team ) }}" alt="{{ $item->nama_team }}" width="100px">
                            @endif
                        </td>
                        <td><a href="{{ route('team.edit', encrypt($item->id) ) }}" class="text-primary">{{ $item->nama_team }}</a></td>
                        <td>{{ $item->jabatan_team }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>

        </div>

    </div>
</div>
<!-- End Recent Sales -->
@endsection