routes/web.php
<?php

use App\Http\Controllers\Back\BlogController;
use App\Http\Controllers\Back\ContactController;
use App\Http\Controllers\Back\DeskripsiTeamController;
use App\Http\Controllers\Back\KategoriController;
use App\Http\Controllers\Back\PesanController;
use App\Http\Controllers\Back\ProfileController;
use App\Http\Controllers\Back\ProfileGambarController;
use App\Http\Controllers\Back\SlideController;
use App\Http\Controllers\Back\TeamController;
use App\Http\Controllers\Front\FrontendController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontendController::class, 'index'])->name('homepage');
Route::get('/blog/detail/{slug}', [FrontendController::class, 'detail'])->name('detail');
Route::post('/kirim-pesan', [FrontendController::class, 'store'])->name('kirimpesan');


Auth::routes([
    'register' => false, // Register Routes...
    'reset' => false, // Reset Password Routes...
    'verify' => false, // Email Verification Routes...
]);


Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');
Route::resource('slide', SlideController::class);
Route::resource('profile', ProfileController::class);
Route::resource('profile-gambar', ProfileGambarController::class);
Route::resource('kategori', KategoriController::class);
Route::resource('blog', BlogController::class);
Route::resource('team', TeamController::class);
Route::resource('deskripsi-team', DeskripsiTeamController::class);
Route::resource('contact', ContactController::class);
Route::resource('pesan', PesanController::class);

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    use HasFactory;

    protected $fillable = [
        'judul',
        'slug',
        'kategori_id',
        'deskripsi',
        'gambar_artikel',
        'user_id',
        'status',
    ];

    public function kategoris()
    {
        return $this->belongsTo(Kategori::class, 'kategori_id', 'id');
    }

    public function users()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }
}

app/Http/Controllers/Back/BlogController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Models\Blog;
use App\Models\Kategori;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;


class BlogController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }


    public function index()
    {
        $blogs = Blog::orderBy('created_at','desc')->get();

        return view('admin.blog.index', compact('blogs'));
    }


    public function create()
    {
        $blogs = Blog::all();
        $kategoris = Kategori::all();

        return view('admin.blog.create', compact('blogs', 'kategoris'));
    }


    public function store(Request $request)
    {
        $request->validate([
            'judul' => 'required|string|unique:blogs,judul',
            'gambar_artikel' => 'required|image|mimes:jpeg,png,jpg,gif,svg',
            'kategori_id' => 'required',
            'deskripsi' => 'required',
        ]);

        if (empty($request->file('gambar_artikel'))) {
            Blog::create([
                'judul' => $request->judul,
                'slug' => Str::slug($request->judul),
                'deskripsi' => $request->deskripsi,
                'kategori_id' => $request->kategori_id,
                'status' => $request->status == TRUE ? '1':'0',
                'user_id' => Auth::id(),
                'gambar_artikel' => $request->gambar_artikel,
            ]);

            toast('Data Gagal dibuat','error');

            return redirect()->route('blog.index');

        } else {

            Blog::create([
                'judul' => $request->judul,
                'slug' => Str::slug($request->judul),
                'deskripsi' => $request->deskripsi,
                'kategori_id' => $request->kategori_id,
                'status' => $request->status == TRUE ? '1':'0',
                'user_id' => Auth::id(),
                'gambar_artikel' => $request->file('gambar_artikel')->store('gambar-artikel'),
            ]);

            toast('Data Berhasil dibuat','success');

            return redirect()->route('blog.index');
        }

        return redirect()->route('admin.blog.index')->with('success', 'Blog created successfully');
    }


    public function edit($id)
    {
        $blog = Blog::findOrFail( decrypt($id) );
        $kategoris = Kategori::all();

        return view('admin.blog.edit', compact('blog', 'kategoris'));
    }



    public function update(Request $request, $id)
    {
        $request->validate([
            'judul' => 'required|string|unique:blogs,judul,'.$id,
            'gambar_artikel' => 'image|mimes:jpeg,png,jpg,gif,svg',
            'kategori_id' => 'required',
            'deskripsi' => 'required',
        ]);

        if (empty($request->file('gambar_artikel'))) {
            $blog = Blog::find($id);
            $blog->update([
                'judul' => $request->judul,
                'slug' => Str::slug($request->judul),
                'deskripsi' => $request->deskripsi,
                'kategori_id' => $request->kategori_id,
                'status' => $request->status,
                'user_id' => Auth::id(),
            ]);

            toast('Data Berhasil diupdate','success');

            return redirect()->route('blog.index');

        } else {
            $blog = Blog::find($id);
            Storage::delete($blog->gambar_artikel);
            $blog->update([
                'judul' => $request->judul,
                'slug' => Str::slug($request->judul),
                'deskripsi' => $request->deskripsi,
                'kategori_id' => $request->kategori_id,
                'status' => $request->status,
                'user_id' => Auth::id(),
                'gambar_artikel' => $request->file('gambar_artikel')->store('gambar-artikel'),
            ]);

            toast('Data Berhasil diupdate','success');

            return redirect()->route('blog.index');
        }
    }


    public function destroy($id)
    {
        $blog = Blog::find($id);
        Storage::delete($blog->gambar_artikel);
        $blog->delete();

        toast('Data Berhasil dihapus','success');

        return redirect()->route('blog.index');
    }


}

resources/views/admin/blog/create.blade.php
@extends('admin.layout.layout', ['menu' => 'componen', 'submenu' => 'blog'])

@section('title', 'Blog')

@section('content')
<div class="">

    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Create Data @yield('title')</h5>

            <!-- General Form Elements -->
            <form action="{{ route('blog.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="row mb-3">
                    <label for="inputText" class="col-sm-2 col-form-label">Judul</label>
                    <div class="col-sm-10">
                        <input name="judul" id="judul" type="text" class="form-control @error('judul') is-invalid @enderror" placeholder="Judul Blog" value="{{ old('judul' ) }}">
                    </div>
                    @error('judul')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>

                <div class="row mb-3">
                    <label for="inputText" class="col-sm-2 col-form-label">Kategori</label>
                    <div class="col-sm-10">
                        <select class="form-select" name="kategori_id" id="kategori_id" aria-label="Default select example" required>
                            <option disabled selected>pilih kategori</option>
                            @foreach ($kategoris as $item)
                            @if (old('kategori_id') == $item->id)
                                <option value="{{ $item->id }}" selected>{{ $item->nama_kategori }}</option>
                            @else
                                <option value="{{ $item->id }}">{{ $item->nama_kategori }}</option>
                            @endif
                            @endforeach
                          </select>
                        {{-- <input name="link_blog" id="link_blog" type="text" class="form-control @error('link_blog') is-invalid @enderror" placeholder="Link blog" value="{{ old('link_blog' ) }}"> --}}
                    </div>
                    @error('kategori_id')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>



                <div class="row mb-3">
                    <label for="inputNumber" class="col-sm-2 col-form-label">Upload Gambar</label>
                    <div class="col-sm-10">
                        <input name="gambar_artikel" id="gambar_artikel" class="form-control @error('gambar_artikel') is-invalid @enderror" type="file" value="{{ old('gambar_artikel' ) }}">
                    </div>
                </div>

                <div class="row mb-5">
                    <label class="col-sm-2 col-form-label">Status</label>
                    <div class="col-sm-10">
                        <div class="form-check form-switch">
                            <input name="status" id="status" class="form-check-input" type="checkbox">
                            @error('status')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                            <label class="form-check-label" for="flexSwitchCheckChecked">Unpublish / Publish</label>
                        </div>
                    </div>
                </div>

                <div class="row mb-5">
                    <label for="inputPassword" class="col-sm-2 col-form-label">Deskripsi</label>
                    <div class="col-sm-10">
                        <textarea name="deskripsi" id="summernote" class="form-control @error('deskripsi') is-invalid @enderror">{{ old('deskripsi' ) }}</textarea>
                    </div>
                    @error('deskripsi')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
                <br>


                <div class="row mb-3">
                    <label class="col-sm-2 col-form-label">Submit Button</label>
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Tambah Data</button>
                        <button type="reset" class="btn btn-danger">Reset Data</button>
                    </div>
                </div>

            </form>
            <!-- End General Form Elements -->

        </div>
    </div>

</div>



@endsection

resources/views/admin/blog/edit.blade.php
@extends('admin.layout.layout', ['menu' => 'componen', 'submenu' => 'blog'])

@section('title', 'Blog')

@section('content')
<div class="">

    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Edit Data @yield('title')</h5>


            <div class="filter">
                <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                    <li class="dropdown-header text-start">
                        <h6>ACTION</h6>
                    </li>

                    <li><a class="dropdown-item" href="{{ route('blog.index') }}">Kembali</a></li>

                </ul>
            </div>

            <!-- General Form Elements -->
            <form action="{{ route('blog.update', $blog->id ) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="row mb-3">
                    <label for="inputText" class="col-sm-2 col-form-label">Judul</label>
                    <div class="col-sm-10">
                        <input name="judul" id="judul" type="text" class="form-control @error('judul') is-invalid @enderror" placeholder="Judul Blog" value="{{ $blog->judul }}">
                    </div>
                    @error('judul')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>

                <div class="row mb-3">
                    <label for="inputText" class="col-sm-2 col-form-label">Kategori</label>
                    <div class="col-sm-10">
                        <select class="form-select" name="kategori_id" id="kategori_id" aria-label="Default select example" required>
                            <option disabled selected>pilih kategori</option>
                            @foreach ($kategoris as $item)
                            @if ($item->id == $blog->kategori_id)
                                <option value="{{ $item->id }}" selected>{{ $item->nama_kategori }}</option>
                            @else
                                <option value="{{ $item->id }}">{{ $item->nama_kategori }}</option>
                            @endif
                            @endforeach
                          </select>
                    </div>
                    @error('kategori_id')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>



                <div class="row mb-3">
                    <label for="inputNumber" class="col-sm-2 col-form-label">Upload Gambar</label>
                    <div class="col-sm-10">
                        <input name="gambar_artikel" id="gambar_artikel" class="form-control @error('gambar_artikel') is-invalid @enderror" type="file" value="{{ old('gambar_artikel' ) }}">
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="inputNumber" class="col-sm-2 col-form-label">Gambar saat ini</label>
                    <div class="col-sm-10">
                        <img src="{{ asset('storage/'.$blog->gambar_artikel) }}" alt="{{ $blog->judul }}" width="100px">
                    </div>
                </div>

                <div class="row mb-5">
                    <label class="col-sm-2 col-form-label">Status</label>
                    <div class="col-sm-10">
                        <div class="form-check form-switch">
                            <input type="hidden" name="status" id="status" value="0">
                            <input name="status" id="status" class="form-check-input" type="checkbox" value="1" {{ $blog->status || old('status', 0) === 1 ? 'checked':'' }}>
                            <label class="form-check-label" for="flexSwitchCheckChecked">Publish</label>

                        </div>
                    </div>
                </div>

                <div class="row mb-5">
                    <label for="inputPassword" class="col-sm-2 col-form-label">Deskripsi</label>
                    <div class="col-sm-10">
                        <textarea name="deskripsi" id="summernote" class="form-control @error('deskripsi') is-invalid @enderror">{{ $blog->deskripsi }}</textarea>
                    </div>
                    @error('deskripsi')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
                <br>


                <div class="row mb-3">
                    <label class="col-sm-2 col-form-label">Submit Button</label>
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Update Data</button>
                    </div>
                </div>

            </form>

            <div class="row mb-3">
                <label class="col-sm-2 col-form-label">Delete Data</label>
                <div class="col-sm-10">
                    <form action="{{ route('blog.destroy', $blog->id ) }}" onsubmit="return confirm('Yakin anda akan menghapus data {{ $blog->judul }}?')" method="POST" class="d-inline">
                        @csrf
                        @method('delete')
                        <button class="btn btn-danger">Delete Data</button>
                    </form>
                </div>
            </div>
            <!-- End General Form Elements -->

        </div>
    </div>

</div>



@endsection

resources/views/admin/blog/index.blade.php
@extends('admin.layout.layout', ['menu' => 'componen', 'submenu' => 'slide'])

@section('title', 'BLog')

@section('content')
<!-- Recent Sales -->
<div class="col-12">
    <div class="card recent-sales overflow-auto">

        <div class="filter">
            <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                <li class="dropdown-header text-start">
                    <h6>ACTION</h6>
                </li>

                <li><a class="dropdown-item" href="{{ route('blog.create') }}">Tambah</a></li>
            </ul>
        </div>

        <div class="card-body">
            <h5 class="card-title">Data <span>| @yield('title')</span></h5>

            <table class="table table-borderless datatable">
                <thead>
                    <tr>
                        <th scope="col">Gambar</th>
                        <th scope="col">Title</th>
                        <th scope="col">Deskripsi</th>
                        <th scope="col">Kategori</th>
                        <th scope="col">Status</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($blogs as $item)
                    <tr>
                        <td>
                            @if ($item->gambar_artikel)
                            <img src="{{ asset('storage/'. $item->gambar_artikel ) }}" alt="{{ $item->judul }}" width="100px">
                            @else
                            <img src="{{ asset('storage/'. $item->gambar_artikel ) }}" alt="{{ $item->judul }}" width="100px">
                            @endif
                        </td>
                        <td><a href="{{ route('blog.edit', encrypt($item->id) ) }}" class="text-primary">{{\Illuminate\Support\Str::words($item->judul, 5,'....') }}</a></td>
                        <td>{!! \Illuminate\Support\Str::words($item->deskripsi, 50,'....') !!}</td>
                        <td>{{ $item->kategoris->nama_kategori }}</td>
                        <td>
                            @if ($item->status == 1)
                            <span class="badge bg-success">Publish</span>
                            @else
                            <span class="badge bg-danger">Unpublish</span>
                            @endif
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>

        </div>

    </div>
</div>
<!-- End Recent Sales -->
@endsection