routes/web.php
<?php

use App\Http\Controllers\Back\BlogController;
use App\Http\Controllers\Back\ContactController;
use App\Http\Controllers\Back\DeskripsiTeamController;
use App\Http\Controllers\Back\KategoriController;
use App\Http\Controllers\Back\PesanController;
use App\Http\Controllers\Back\ProfileController;
use App\Http\Controllers\Back\ProfileGambarController;
use App\Http\Controllers\Back\SlideController;
use App\Http\Controllers\Back\TeamController;
use App\Http\Controllers\Front\FrontendController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontendController::class, 'index'])->name('homepage');
Route::get('/blog/detail/{slug}', [FrontendController::class, 'detail'])->name('detail');
Route::post('/kirim-pesan', [FrontendController::class, 'store'])->name('kirimpesan');


Auth::routes([
    'register' => false, // Register Routes...
    'reset' => false, // Reset Password Routes...
    'verify' => false, // Email Verification Routes...
]);


Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');
Route::resource('slide', SlideController::class);
Route::resource('profile', ProfileController::class);
Route::resource('profile-gambar', ProfileGambarController::class);
Route::resource('kategori', KategoriController::class);
Route::resource('blog', BlogController::class);
Route::resource('team', TeamController::class);
Route::resource('deskripsi-team', DeskripsiTeamController::class);
Route::resource('contact', ContactController::class);
Route::resource('pesan', PesanController::class);

app/Models/Kategori.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kategori extends Model
{
    use HasFactory;

    protected $fillable = [
        'nama_kategori',
        'slug'
    ];

    public function artikels()
    {
        return $this->hasMany(Blog::class, 'kategori_id');
    }
}

app/Http/Controllers/Back/KategoriController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Models\Kategori;
use Illuminate\Http\Request;
use Illuminate\Support\Str;


class KategoriController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }


    public function index()
    {
        $kategoris = Kategori::all();

        return view('admin.kategori.index', compact('kategoris'));
    }


    public function create()
    {
        $kategoris = Kategori::all();

        return view('admin.kategori.create', compact('kategoris'));
    }


    public function store(Request $request)
    {
        request()->validate([
            'nama_kategori' => 'required',
        ]);

        Kategori::create([
            'nama_kategori' => $request->nama_kategori,
            'slug' => Str::slug($request->nama_kategori)
        ]);

        toast('Data Berhasil dibuat','success');

        return redirect()->route('kategori.index')->with('success', 'Data berhasil ditambah');
    }


    public function edit($id)
    {
        $kategori = Kategori::find(decrypt($id));

        return view('admin.kategori.edit', compact('kategori'));
    }


    public function update(Request $request, $id)
    {
        request()->validate([
            'nama_kategori' => 'required',
        ]);


        $data = $request->all();
        $data['slug'] = Str::slug($request->nama_kategori);

        $categories = Kategori::findOrFail($id);
        $categories->update($data);

        toast('Data Berhasil diupdate','success');

        return redirect()->route('kategori.index')->with('success', 'Data berhasil diubah');
    }


    public function destroy($id)
    {
        Kategori::destroy($id);

        toast('Data Berhasil dihapus','success');

        return redirect()->route('kategori.index')->with('success', 'Data berhasil dihapus');
    }
}

resources/views/admin/kategori/create.blade.php
@extends('admin.layout.layout', ['menu' => 'componen', 'submenu' => 'slide'])

@section('title', 'Kategori')

@section('content')
    <div class="">

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Create Data @yield('title')</h5>

                <!-- General Form Elements -->
                <form action="{{ route('kategori.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="row mb-3">
                        <label for="inputText" class="col-sm-2 col-form-label">Nama Kategori</label>
                        <div class="col-sm-10">
                            <input name="nama_kategori" id="nama_kategori" type="text" class="form-control @error('nama_kategori') is-invalid @enderror" placeholder="Nama Kategori" value="{{ old('nama_kategori' ) }}">
                        </div>
                        @error('nama_kategori')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>

                    <div class="row mb-3">
                        <label class="col-sm-2 col-form-label">Submit Button</label>
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary">Tambah Data</button>
                            <button type="reset" class="btn btn-danger">Reset Data</button>
                        </div>
                    </div>

                </form>
                <!-- End General Form Elements -->

            </div>
        </div>

    </div>

@endsection

resources/views/admin/kategori/edit.blade.php
@extends('admin.layout.layout', ['menu' => 'componen', 'submenu' => 'slide'])

@section('title', 'Slide')

@section('content')
<div class="">

    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Edit Data @yield('title')</h5>

            <div class="filter">
                <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                    <li class="dropdown-header text-start">
                        <h6>ACTION</h6>
                    </li>

                    <li><a class="dropdown-item" href="{{ route('kategori.index') }}">Kembali</a></li>

                </ul>
            </div>

            {{-- <a href="{{ route('slide.index') }}" class="btn btn-primary">Back</a> --}}

            <!-- General Form Elements -->
            <form action="{{ route('kategori.update', $kategori->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="row mb-3">
                    <label for="inputText" class="col-sm-2 col-form-label">Nama Kategori</label>
                    <div class="col-sm-10">
                        <input name="nama_kategori" id="nama_kategori" type="text" class="form-control @error('nama_kategori') is-invalid @enderror" placeholder="Nama Kategri" value="{{ $kategori->nama_kategori }}">
                    </div>
                    @error('nama_kategori')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>

                <div class="row mb-3">
                    <label class="col-sm-2 col-form-label">Submit Button</label>
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Update Data</button>
                    </div>
                </div>

            </form>

            <div class="row mb-3">
                <label class="col-sm-2 col-form-label">Delete Data</label>
                <div class="col-sm-10">
                    <form action="{{ route('kategori.destroy', $kategori->id ) }}" onsubmit="return confirm('Yakin anda akan menghapus data {{ $kategori->nama_kategori }}?')" method="POST" class="d-inline">
                        @csrf
                        @method('delete')
                        <button class="btn btn-danger">Delete Data</button>
                    </form>
                </div>
            </div>
            <!-- End General Form Elements -->

        </div>
    </div>

</div>

@endsection

resources/views/admin/kategori/index.blade.php
@extends('admin.layout.layout', ['menu' => 'componen', 'submenu' => 'kategori'])

@section('title', 'Kategori')

@section('content')
<!-- Recent Sales -->
<div class="col-12">
    <div class="card recent-sales overflow-auto">

        <div class="filter">
            <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                <li class="dropdown-header text-start">
                    <h6>ACTION</h6>
                </li>

                <li><a class="dropdown-item" href="{{ route('kategori.create') }}">Tambah</a></li>
            </ul>
        </div>

        <div class="card-body">
            <h5 class="card-title">Data <span>| @yield('title')</span></h5>

            <table class="table table-borderless datatable">
                <thead>
                    <tr>
                        <th scope="col">Nama Kategori</th>
                        <th scope="col">Slug</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($kategoris as $item)
                    <tr>
                        <td><a href="{{ route('kategori.edit', encrypt($item->id) ) }}" class="text-primary">{{ $item->nama_kategori }}</a></td>
                        <td>{{ $item->slug }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>

        </div>

    </div>
</div>
<!-- End Recent Sales -->
@endsection